server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security_authority
    data-username: root
    data-password: root
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: security.oauth.source.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    security.oauth.source: debug