server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security_authority
    data-username: root
    data-password: root

mybatis:
  type-aliases-package: com.spring.security.domian
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.spring.security: debug